ip = "127.0.0.1"
port = "2224"
username = "go"
password = "forever"
pidfile = "/var/log/goforever.pid"
logfile = "/var/log/goforever.log"
errfile = "/var/log/goforever.log"

[[process]]
name = "ngrok"
command = "/bin/ngrok"
args = [ "start", "--all", "--config=/etc/ngrok.yml" ]
pidfile = "/var/run/ngrok.pid"
logfile = "/var/log/ngrok.log"
errfile = "/var/log/ngrok.log"
respawn = 1
delay = "1m"
ping = "30s"
